# Generated by Django 4.1.7 on 2023-03-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NUM', 'Numeric'), ('PER', 'Percent')], max_length=3, verbose_name='Type')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('created_in', models.DateField(verbose_name='Start Date')),
                ('expired_in', models.DateField(verbose_name='End Date')),
                ('value', models.FloatField(default=0, verbose_name='Value')),
                ('count', models.IntegerField(default=-1, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Discount Ticket',
                'verbose_name_plural': 'Discount Tickets',
            },
        ),
    ]
