# Generated by Django 4.1.7 on 2023-03-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('products', '0005_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField(default=0.1, verbose_name='Tax Rate')),
                ('status', models.CharField(choices=[('Deliver', 'Delivered'), ('Send', 'Sending'), ('Return', 'Returned'), ('Cancel', 'Canceled')], default='Send', max_length=7, verbose_name='Status')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('address', models.TextField(verbose_name='Address')),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('discount_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='orders.discountticket', verbose_name='Discount Code')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounts.shopuser', verbose_name='Shop user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
