# Generated by Django 4.1.7 on 2023-03-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('products', '0005_product'),
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Is Registered')),
                ('created_in', models.DateField(auto_now_add=True, verbose_name='Created In')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopuser', verbose_name='Shop User')),
            ],
            options={
                'verbose_name': 'Temporary Cart',
                'verbose_name_plural': 'Temporary Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.temporarycart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
