# Generated by Django 4.1.7 on 2023-03-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_description_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NUM', 'Numeric'), ('PER', 'Percent')], max_length=3, verbose_name='Type')),
                ('created_in', models.DateField(verbose_name='Start Date')),
                ('expired_in', models.DateField(verbose_name='End Date')),
                ('value', models.FloatField(default=0, verbose_name='value')),
                ('count', models.IntegerField(default=-1, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
