# Generated by Django 4.1.7 on 2023-03-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('description', models.TextField(default='No description', verbose_name='Description')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='image')),
                ('balance', models.IntegerField(verbose_name='Balance')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.brand', verbose_name='Brand')),
                ('category', models.ManyToManyField(to='products.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
